rendering: False               # if render the env
nb_experiments: 5              # number of experiments
random_seed: 1234              # random seed
total_eps: 5000                # total episodes
is_learning: True              # training flag
eps_per_epoch: 10              # episodes per epoch
max_start_nullops: 0           
is_testing: True               # Testing flag
eps_per_test: 100              # episodes per testing
eps_max_len: 300               # max episodes length
folder_location: '/results/'   # the location to save the results
test: False

epsilon: 1.0                   # epsilon for epsilon-greedy
annealing: False               # if anneal
final_epsilon: 1.0             # final epsilon after annealing
test_epsilon: 0.0              # epsilon during testing

gamma: 0.99
learning_rate: 0.001
minibatch_size: 32
history_len: 1
replay_max_size: 10000
replay_min_size: 1000
learning_frequency: 4
update_freq: 100              # how frequent to update the model
action_dim: 1                 # dimension of action vector
num_units: 250                # number of units of hidden dim of the DQN
outf: 'outputs/'              # output directory
cuda: True
